### ISSUE TITLE
Latest Release?

### ISSUE THREAD

**Issue by JanC** [vranki/ExtPlane#53]
Hi,
what is the latest stable release? In the release github page there are many untagged releases. I believe you should run the Travis deploy step only on tagged commits using `tags: true`

```
deploy:
  provider: releases
  api_key:
    secure: mGPELl1Bc2nkK6JPsyorKkYC7uAwP4H5AfGev5vpIoOfC0Kp/ubRNVKE3771/tzPw4P2QpYDTvl9dL0hGJcoVEUeomRuBoNViueAzpZVJQSNo68lbse+SAMi2JHSs+p0uyDdIVY51Hu5NFQYnDWvxIgbv4RF8mztymdSS1CtDlU=
  file:
    - "extplane-plugin.zip"
    - "extplane-transformer.zip"
  skip_cleanup: true
  on:
    tags: true
```
